version: '3.8'

services:
  ms-database:
    container_name: ms-database
    image: mongo:8.0.4
    ports:
      - 27017:27017
    restart: always
    networks:
      - vcnafacul-network

  ms-simulado:
    container_name: ms-simulado
    image: vcnafacul/simulado:latest
    ports:
      - 3000:3000
    env_file:
      - .env
    restart: always
    depends_on:
      - ms-database
    networks:
      - vcnafacul-network
    command: sh -c "npm run migration:run && npm run seed"

  api-database:
    container_name: api-database
    image: mysql:9.1.0
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mysql
    networks:
      - vcnafacul-network

  api-vcnafacul:
    container_name: api-vcnafacul
    image: vcnafacul/api:latest
    ports:
      - 3333:3333
    env_file:
      - .env
    restart: always
    depends_on:
      - api-database
      - ms-simulado
    networks:
      - vcnafacul-network
    command: sh -c "npm run migration:run && npm run seed"
    # command: ["yarn", "test:local"]
    # command: ["npm", "run", "seed"]
   
networks:
  vcnafacul-network:
    driver: bridge