import { Permissions } from './permissions';

export const PERMISSION_FIELD_MAP: Record<Permissions, string> = {
  [Permissions.validarCursinho]: 'validarCursinho',
  [Permissions.alterarPermissao]: 'alterarPermissao',
  [Permissions.criarQuestao]: 'criarQuestao',
  [Permissions.visualizarQuestao]: 'visualizarQuestao',
  [Permissions.validarQuestao]: 'validarQuestao',
  [Permissions.uploadNews]: 'uploadNews',
  [Permissions.visualizarProvas]: 'visualizarProvas',
  [Permissions.cadastrarProvas]: 'cadastrarProvas',
  [Permissions.visualizarDemanda]: 'visualizarDemanda',
  [Permissions.uploadDemanda]: 'uploadDemanda',
  [Permissions.validarDemanda]: 'validarDemanda',
  [Permissions.gerenciadorDemanda]: 'gerenciadorDemanda',
  [Permissions.gerenciarProcessoSeletivo]: 'gerenciarProcessoSeletivo',
  [Permissions.gerenciarColaboradores]: 'gerenciarColaboradores',
  [Permissions.gerenciarTurmas]: 'gerenciarTurmas',
  [Permissions.visualizarTurmas]: 'visualizarTurmas',
  [Permissions.gerenciarEstudantes]: 'gerenciarEstudantes',
  [Permissions.visualizarEstudantes]: 'visualizarEstudantes',
  [Permissions.gerenciarPermissoesCursinho]: 'gerenciarPermissoesCursinho',
  [Permissions.visualizarMinhasInscricoes]: 'visualizarMinhasInscricoes',
  [Permissions.gerenciarFormularioGlobal]: 'gerenciarFormularioGlobal',
  [Permissions.gerenciarFormulario]: 'gerenciarFormulario',
  [Permissions.gerenciarTemas]: 'gerenciarTemas',
  [Permissions.revisarRedacoes]: 'revisarRedacoes',
  [Permissions.revisarTodasRedacoes]: 'revisarTodasRedacoes',
  [Permissions.supportAgent]: 'supportAgent',
  [Permissions.partnerPrepSupportAgent]: 'partnerPrepSupportAgent',
  [Permissions.editarMateriasFrentes]: 'editarMateriasFrentes',
  [Permissions.visualizarProvasCursinho]: 'visualizarProvasCursinho',
  [Permissions.cadastrarProvasCursinho]: 'cadastrarProvasCursinho',
};
